# Generated by Django 5.2.14 on 2026-05-28 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionrecord',
            name='approval_stage',
            field=models.CharField(default='ANALYST_REVIEW', max_length=32),
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='calc_trace',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='co2e_kg',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='factor_region',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='factor_source',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='factor_unit',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='factor_value',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='factor_version',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='factor_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='quality_flags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='ingestionjob',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingestionjob',
            name='idempotency_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='ingestionjob',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='ingestionjob',
            name='quality_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='ingestionjob',
            name='quality_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='ingestionjob',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingestionjob',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='ingestion_uploads/'),
        ),
        migrations.AlterField(
            model_name='ingestionjob',
            name='status',
            field=models.CharField(choices=[('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='PROCESSING', max_length=16),
        ),
        migrations.CreateModel(
            name='ApprovalWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stage', models.CharField(choices=[('ANALYST_REVIEW', 'Analyst Review'), ('REVIEWER_REVIEW', 'Reviewer Review'), ('MANAGER_SIGNOFF', 'Manager Signoff'), ('COMPLETED', 'Completed')], default='ANALYST_REVIEW', max_length=32)),
                ('is_completed', models.BooleanField(default=False)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval_workflow', to='core.emissionrecord')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_workflows', to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('ANALYST_REVIEW', 'Analyst Review'), ('REVIEWER_REVIEW', 'Reviewer Review'), ('MANAGER_SIGNOFF', 'Manager Signoff'), ('COMPLETED', 'Completed')], max_length=32)),
                ('decision', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FLAGGED', 'Flagged')], max_length=16)),
                ('note', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_decisions', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='core.approvalworkflow')),
            ],
            options={
                'ordering': ['decided_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='core.ingestionjob')),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='core.emissionrecord')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BenchmarkSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(max_length=64)),
                ('period', models.CharField(default='monthly', max_length=16)),
                ('date', models.DateField()),
                ('value', models.DecimalField(decimal_places=6, max_digits=16)),
                ('denominator', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benchmark_snapshots', to='core.tenant')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DataQualitySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_rows', models.IntegerField(default=0)),
                ('valid_rows', models.IntegerField(default=0)),
                ('flagged_rows', models.IntegerField(default=0)),
                ('failed_rows', models.IntegerField(default=0)),
                ('issue_breakdown', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quality_snapshot', to='core.ingestionjob')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_snapshots', to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(blank=True, max_length=32)),
                ('scope', models.CharField(blank=True, choices=[('SCOPE_1', 'Scope 1'), ('SCOPE_2', 'Scope 2'), ('SCOPE_3', 'Scope 3')], max_length=16)),
                ('factor_kind', models.CharField(choices=[('ACTIVITY_TO_CO2E', 'Activity to CO2e')], default='ACTIVITY_TO_CO2E', max_length=32)),
                ('input_unit', models.CharField(max_length=64)),
                ('output_unit', models.CharField(default='kg_co2e', max_length=32)),
                ('region', models.CharField(blank=True, max_length=64)),
                ('year', models.IntegerField()),
                ('value', models.DecimalField(decimal_places=8, max_digits=16)),
                ('version', models.CharField(max_length=64)),
                ('source_name', models.CharField(blank=True, max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emission_factors', to='core.tenant')),
            ],
            options={
                'ordering': ['-year', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ReductionTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('scope', models.CharField(blank=True, choices=[('SCOPE_1', 'Scope 1'), ('SCOPE_2', 'Scope 2'), ('SCOPE_3', 'Scope 3')], max_length=16)),
                ('baseline_year', models.IntegerField()),
                ('baseline_value', models.DecimalField(decimal_places=4, max_digits=16)),
                ('target_year', models.IntegerField()),
                ('target_value', models.DecimalField(decimal_places=4, max_digits=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_targets', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reduction_targets', to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='SimulationScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('assumptions', models.JSONField(blank=True, default=dict)),
                ('projected_delta_kg', models.DecimalField(decimal_places=4, default=0, max_digits=16)),
                ('projected_total_kg', models.DecimalField(decimal_places=4, default=0, max_digits=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_scenarios', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulation_scenarios', to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='DataQualityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(blank=True, max_length=32)),
                ('code', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('rule_config', models.JSONField(blank=True, default=dict)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_rules', to='core.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'code')},
            },
        ),
        migrations.CreateModel(
            name='IngestionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('SAP_FUEL', 'SAP Fuel'), ('UTILITY_ELECTRICITY', 'Utility Electricity'), ('TRAVEL', 'Travel')], max_length=32)),
                ('name', models.CharField(max_length=120)),
                ('vendor_name', models.CharField(blank=True, max_length=120)),
                ('column_mapping', models.JSONField(blank=True, default=dict)),
                ('required_columns', models.JSONField(blank=True, default=list)),
                ('validation_rules', models.JSONField(blank=True, default=dict)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_templates', to='core.tenant')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('tenant', 'source_type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ANALYST', 'Analyst'), ('REVIEWER', 'Reviewer'), ('MANAGER', 'Manager'), ('ADMIN', 'Admin')], default='ANALYST', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('tenant', 'user')},
            },
        ),
    ]
