# Generated by Django 5.2.14 on 2026-05-28 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_emissionrecord_approval_stage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingestionjob',
            name='source_type',
            field=models.CharField(choices=[('SAP_FUEL', 'SAP Fuel'), ('SAP_PROCUREMENT', 'SAP Procurement'), ('UTILITY_ELECTRICITY', 'Utility Electricity'), ('TRAVEL', 'Travel')], max_length=32),
        ),
        migrations.AlterField(
            model_name='ingestiontemplate',
            name='source_type',
            field=models.CharField(choices=[('SAP_FUEL', 'SAP Fuel'), ('SAP_PROCUREMENT', 'SAP Procurement'), ('UTILITY_ELECTRICITY', 'Utility Electricity'), ('TRAVEL', 'Travel')], max_length=32),
        ),
    ]
