# Generated by Django 5.2.14 on 2026-05-27 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomaly_type', models.CharField(choices=[('OUTLIER', 'Statistical Outlier (Z-Score)'), ('DUPLICATE', 'Potential Duplicate'), ('UNUSUAL_INCREASE', 'Unusual Increase (>20%)'), ('UNUSUAL_DECREASE', 'Unusual Decrease (>20%)'), ('ZERO_VALUE', 'Zero or Null Value'), ('UNIT_MISMATCH', 'Unit Inconsistency')], max_length=32)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=16)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('acknowledged_by', models.TextField(blank=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='core.emissionrecord')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_flags', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('record', 'anomaly_type')},
            },
        ),
        migrations.CreateModel(
            name='EmissionsSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('total', 'Total'), ('daily', 'Daily'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='total', max_length=32)),
                ('date', models.DateField(blank=True, null=True)),
                ('scope_1_total', models.DecimalField(decimal_places=4, default=0, max_digits=16)),
                ('scope_2_total', models.DecimalField(decimal_places=4, default=0, max_digits=16)),
                ('scope_3_total', models.DecimalField(decimal_places=4, default=0, max_digits=16)),
                ('grand_total', models.DecimalField(decimal_places=4, default=0, max_digits=16)),
                ('source_breakdown', models.JSONField(blank=True, default=dict)),
                ('activity_breakdown', models.JSONField(blank=True, default=dict)),
                ('record_count', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emissions_summaries', to='core.tenant')),
            ],
            options={
                'verbose_name_plural': 'Emissions Summaries',
                'ordering': ['-last_updated'],
                'unique_together': {('tenant', 'period', 'date')},
            },
        ),
        migrations.CreateModel(
            name='TrendAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(max_length=32)),
                ('scope', models.CharField(max_length=16)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly')], max_length=16)),
                ('total_emissions', models.DecimalField(decimal_places=4, max_digits=16)),
                ('record_count', models.IntegerField()),
                ('avg_emissions', models.DecimalField(decimal_places=4, max_digits=16)),
                ('min_emissions', models.DecimalField(decimal_places=4, max_digits=16, null=True)),
                ('max_emissions', models.DecimalField(decimal_places=4, max_digits=16, null=True)),
                ('percent_change', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trend_analyses', to='core.tenant')),
            ],
            options={
                'verbose_name_plural': 'Trend Analyses',
                'ordering': ['-period_end'],
                'unique_together': {('tenant', 'source_type', 'scope', 'period_start', 'period_end', 'period_type')},
            },
        ),
    ]
